---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    app: {{ include "mychart.labels" . }}
  namespace: {{ include "mychart.namespace" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mychart.labels" . }}
  strategy:
    {{- if eq .Values.strategy.type "RollingUpdate"}}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
    type: {{ .Values.strategy.type }}
  template:
    metadata:
      labels:
        app: {{ include "mychart.labels" . }}
    spec:
      containers:
      - name: {{ include "mychart.fullname" . }}
      {{- if .Values.envs }}
      {{- with .Values.envs }}
        env:
        {{- toYaml . | nindent 8}}
      {{- end }}
      {{- end }}
        
        {{- if ne .Values.image.tag "" }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- else }}
        image: "{{ .Values.image.repository }}"
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.livenessProbe }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10}}  
        {{- end }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10}}  
        {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      {{- if .Values.hostAliases }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}