# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


nameOverride: ""
fullnameOverride: ""
labelsOverride: ""
namespaceOverride: ""

replicaCount: 0

strategy:
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 0
  type: RollingUpdate

# envs: []

image:
  repository: ""
  tag: ""
  pullPolicy: Always

imagePullSecrets:
  - name: reg-pegah-credit

podSecurityContext: {}
  # fsGroup: 2000

service:
  type: ClusterIP
  port:
  - port: 5000
    protocol: TCP

resources: {}
  # limits:
  #   cpu: "1"
  #   memory: 1G
  # requests:
  #   cpu: "1"
  #   memory: 1G

tolerations:
  - effect: NoSchedule
    key: common-servers 
    operator: Exists


# livenessProbe: {}
#   # httpGet:
#   #   path: /actuator/health
#   #   port: 8080
#   #   scheme: HTTP

# readinessProbe: {}
#   # httpGet: 
#   #   path: /actuator/health
#   #   port: 8080
#   #   scheme: HTTP

# hostAliases:
#   - hostnames:
#     - n1.rs1.c1.mongo.backtory.com
#     ip: 172.16.17.201
